# Generated by Django 6.0.3 on 2026-04-02 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('db_type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB'), ('clickhouse', 'ClickHouse')], max_length=20)),
                ('config', models.JSONField()),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Offline', 'Offline'), ('Untested', 'Untested')], default='Untested', max_length=10)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connections',
            },
        ),
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_size', models.IntegerField(default=1000)),
                ('query_metadata', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROGRESS', 'Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('result_preview', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.connection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extraction_jobs',
            },
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=512)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], max_length=4)),
                ('source_metadata', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='api.extractionjob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_metadata',
            },
        ),
        migrations.CreateModel(
            name='FileAccessControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('VIEWER', 'Viewer'), ('DOWNLOADER', 'Downloader')], max_length=12)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
                ('file_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='api.filemetadata')),
            ],
            options={
                'db_table': 'file_access_control',
            },
        ),
        migrations.CreateModel(
            name='ProcessedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('row_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.extractionjob')),
            ],
            options={
                'db_table': 'processed_records',
                'ordering': ['row_index'],
            },
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['db_type'], name='idx_connection_db_type'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['job_id', 'status'], name='idx_job_id_status'),
        ),
        migrations.AddIndex(
            model_name='extractionjob',
            index=models.Index(fields=['owner', 'status'], name='idx_owner_status'),
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['owner'], name='idx_file_owner'),
        ),
        migrations.AddIndex(
            model_name='fileaccesscontrol',
            index=models.Index(fields=['user'], name='idx_fac_user'),
        ),
        migrations.AlterUniqueTogether(
            name='fileaccesscontrol',
            unique_together={('file_metadata', 'user')},
        ),
        migrations.AddIndex(
            model_name='processedrecord',
            index=models.Index(fields=['job'], name='idx_record_job'),
        ),
    ]
